eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: shopGaetway

#网关的IP地址
server:
  port: 9000
zuul:
  routes:
    shop-cate-api:
      path: /cate/**
    shop-good-api:
      path: /goods/**
    shop-member-api:
      path: /member/**
    shop-cart-api:
      path: /cart/**
fh:
  shop:
    checkUrls: /api/member/loginOut,/api/member/findMember,/api/cart/addCart,/api/cart/queryCart,/api/findSku #登陆后才能访问的






